//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyPagination.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int ID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Modifier { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
